movie_data = {
    "AVATAR": "A visually stunning sci-fi film set on the alien world of Pandora.",
    "TITANIC": "A film about a famous shipwreck and a love story on the Titanic.",
    "INCEPTION": "A mind-bending thriller directed by Christopher Nolan.",
    "JAMES BOND": "A famous spy character known for his gadgets and charm.",
    "HARRY POTTER": "A young wizard's journey to defeat the dark wizard Voldemort.",
    "FORREST GUMP": "A heartwarming story of a man's journey through American history.",
    "THE GODFATHER": "A classic crime drama directed by Francis Ford Coppola.",
    "IRON MAN": "A Marvel superhero known for his high-tech armor.",
    "GONEWITHTHEWIND": "A classic epic set during the American Civil War.",
    "ROCKY": "A boxing drama featuring the iconic character Rocky Balboa.",
    "ALADDIN": "A Disney animated film about a young man and his magic lamp.",
    "JOKER": "A psychological thriller about the origin of Batman's arch-nemesis.",
    "SHOLAY": "A classic Bollywood film known for its iconic characters.",
    "DILWALEDULHANIALEJAYENGE": "A Bollywood romance that redefined love stories.",
    "KABIRSINGH": "A Bollywood film about a brilliant but self-destructive surgeon.",
    "SPIDERMAN": "A Marvel superhero with wall-crawling abilities.",
    "JURASSICPARK": "A science fiction adventure featuring cloned dinosaurs.",
    "TOYSTORY": "A heartwarming Pixar animated film about toys that come to life.",
    "INTERSTELLAR": "A Christopher Nolan sci-fi film about space exploration.",
    "THEMATRIX": "A sci-fi classic featuring a virtual reality world and Neo's journey.",
    "FROZEN": "A Disney animated film about two sisters and the power of love.",
    "TRANSFORMERS": "A sci-fi action film featuring shape-shifting robots.",
    "E.T.": "A classic film about a boy and his alien friend.",
    "GLADIATOR": "A historical epic starring Russell Crowe as a Roman general.",
    "JAWS": "A classic thriller about a great white shark terrorizing a beach town.",
    "THELIONKING": "A beloved Disney animated film about a lion cub's journey.",
    "ALIEN": "A sci-fi horror film featuring a deadly extraterrestrial creature.",
    "THEMUMMY": "An adventure film with a resurrected ancient Egyptian priest.",
    "PIRATESOFTHECARIBBEAN": "A swashbuckling adventure with Captain Jack Sparrow.",
    "TERMINATOR": "A sci-fi classic featuring a cyborg sent back in time.",
    "BATMAN": "The dark knight of Gotham City, a DC Comics superhero.",
    "THOR": "A Marvel superhero based on the Norse god of thunder.",
    "SUPERMAN": "The iconic DC Comics superhero with superhuman abilities.",
    "MADMAX": "A post-apocalyptic action film featuring Max Rockatansky.",
    "FIGHTCLUB": "A David Fincher film with a unique take on consumer culture.",
    "BLADE": "A Marvel superhero known for hunting vampires.",
    "MIB": "The Men in Black, a secret organization that monitors extraterrestrial activity.",
    "ROBOCOP": "A sci-fi film about a cyborg law enforcement officer.",
    "CROUCHINGTIGERHIDDENDRAGON": "An epic martial arts film directed by Ang Lee.",
    "GLADIATOR": "A historical epic starring Russell Crowe as a Roman general.",
    "SCHINDLERSLIST": "A Steven Spielberg film about a man who saved Jewish lives during the Holocaust.",
    "BRAVEHEART": "A historical epic featuring William Wallace's fight for Scottish independence.",
    "GANDHI": "A biographical film about the life of Mahatma Gandhi.",
    "SHERLOCKHOLMES": "A brilliant detective created by Sir Arthur Conan Doyle.",
    "CITIZENKANE": "A classic film often regarded as one of the greatest of all time.",
    "CASABLANCA": "A timeless romantic drama set during World War II.",
    "GOLDFINGER": "A James Bond film known for its iconic villain, Auric Goldfinger.",
    "PULPFICTION": "A Quentin Tarantino film known for its nonlinear storytelling.",
    "GOODFELLAS": "A crime drama directed by Martin Scorsese.",
    "SCARFACE": "A crime film character, Tony Montana, known for the line 'Say hello to my little friend.'",
    "THEEXORCIST": "A horror film about a young girl possessed by a demonic entity.",
    "PSYCHO": "A classic thriller directed by Alfred Hitchcock.",
    "THEGRADUATE": "A coming-of-age film starring Dustin Hoffman.",
    "SINGININTHERAIN": "A classic musical comedy film.",
    "CITYLIGHTS": "A silent romantic comedy-drama directed by and starring Charlie Chaplin.",
    "GONEWITHTHEWIND": "A classic epic set during the American Civil War.",
    "THERESERVOIRDOGS": "A Quentin Tarantino film known for its ensemble cast.",
    "HITCHCOCK": "A biographical drama about the iconic filmmaker Alfred Hitchcock.",
    "SUNSETBOULEVARD": "A classic film noir about faded Hollywood stars.",
    "RAGINGBULL": "A biographical sports drama featuring Jake LaMotta.",
    "GODFATHER": "A classic crime drama directed by Francis Ford Coppola.",
    "AFTERHOURS": "A dark comedy film directed by Martin Scorsese.",
    "CASINO": "A crime drama directed by Martin Scorsese.",
    "AVIATOR": "A biographical drama about the life of Howard Hughes.",
    "SHUTTLE": "A thriller about a group of people stranded in an airport shuttle.",
    "AQUAMAN": "A DC Comics superhero known for his aquatic abilities.",
    "FRODO": "A character from The Lord of the Rings, known for his journey to Mordor.",
    "VOLDEMORT": "The main antagonist in the Harry Potter series.",
    "HANNIBALLECTER": "A brilliant but psychotic serial killer in The Silence of the Lambs.",
    "WONDERWOMAN": "A DC Comics superheroine known for her strength and courage.",
    "NEMO": "A character from Finding Nemo, a clownfish searching for his son.",
    "WALLE": "A Pixar robot tasked with cleaning a polluted Earth.",
    "BUZZLIGHTYEAR": "A space ranger toy in Toy Story, known for his catchphrase 'To infinity and beyond.'",
    "PREDATOR": "An extraterrestrial hunter featured in the Predator film series.",
    "RIDDICK": "A character played by Vin Diesel in the Chronicles of Riddick series.",
    "RAMBO": "A character known for his action-packed military missions.",
    "JUMANJI": "An adventure film based on a magical board game.",
    "VENOM": "A Marvel antihero known for his symbiotic relationship with an alien parasite.",
    "MADHATTER": "A character from Alice in Wonderland known for his eccentricity.",
    "ZORRO": "A masked vigilante character known for his sword-fighting skills.",
    "CINDERELLA": "A Disney princess known for her magical transformation.",
    "MOANA": "A Disney princess and navigator on a daring voyage.",
    "MULAN": "A Disney character who disguises herself as a man to take her father's place in the army.",
    "FRODO": "A character from The Lord of the Rings, known for his journey to Mordor.",
    "VOLDEMORT": "The main antagonist in the Harry Potter series.",
    "HANNIBALLECTER": "A brilliant but psychotic serial killer in The Silence of the Lambs.",
    "WONDERWOMAN": "A DC Comics superheroine known for her strength and courage.",
    "NEMO": "A character from Finding Nemo, a clownfish searching for his son.",
    "WALLE": "A Pixar robot tasked with cleaning a polluted Earth.",
    "BUZZLIGHTYEAR": "A space ranger toy in Toy Story, known for his catchphrase 'To infinity and beyond.'",
    "PREDATOR": "An extraterrestrial hunter featured in the Predator film series.",
    "RIDDICK": "A character played by Vin Diesel in the Chronicles of Riddick series.",
    "RAMBO": "A character known for his action-packed military missions.",
    "JUMANJI": "An adventure film based on a magical board game.",
    "VENOM": "A Marvel antihero known for his symbiotic relationship with an alien parasite.",
    "MADHATTER": "A character from Alice in Wonderland known for his eccentricity.",
    "ZORRO": "A masked vigilante character known for his sword-fighting skills.",
    "CINDERELLA": "A Disney princess known for her magical transformation.",
    "MOANA": "A Disney princess and navigator on a daring voyage.",
    "MULAN": "A Disney character who disguises herself as a man to take her father's place in the army."
}
